### ISSUE TITLE
Apply validation rules in validation.yaml

### ISSUE THREAD

**Issue by tompollard** [tompollard/omopetl#20]
As part of the configuration (in `config/`) we allow users to provide custom validation rules for their mapping. e.g.:

```
validation:
  person:
    - column: birth_datetime
      rule: range
      min: "1900-01-01"
      max: "2023-12-31"
  visit_occurrence:
    - column: visit_start_datetime
      rule: not_null
    - column: visit_occurrence_id
      rule: unique
  condition_occurrence:
    - column: condition_concept_id
      rule: valid_concept
      vocabulary: SNOMED
  measurement:
    - column: measurement_source_value
      rule: regex
      pattern: "^[A-Z0-9_-]+$"
```

Right now, we aren't applying these validation rules.
