### ISSUE TITLE
Provide transformation which drops duplicates

### ISSUE THREAD

**Issue by briangow** [tompollard/omopetl#60]
When generating a lookup table, it is often desired that there are not duplicate rows in the lookup. This ensures that when the lookup is referenced at a later time that the output table doesn't have more rows than expected. Please provide a transformation which allows dropping duplicates.

**Comment by tompollard** [comment]
This is an unusual transformation because it doesn't fit into the current "column-based" approach. 

Currently each transformation adds a new column based on a set of rules, but a de-duplication transformation would be applied across multiple columns.

We could add a "pre-processing" step to the workflow, but I'd prefer to deal with this later if necessary.

For the meantime, can we do a de-duplication step manually? i.e. if there is a lookup table with duplicate concepts then this seems like an issue with the table.

**Comment by tompollard** [comment]
Or I guess the issue here is that there is a problem with the way we are generating lookups? It would be helpful to see an example, so that I can understand why we end up with duplicates in the lookup.

**Comment by briangow** [comment]
@tompollard , this issue can be seen in the demo from this repo: omopetl/templates/demo/config/mappings.yaml . The `tmp_subject_race` table that is generated during the demo has duplicate rows, which isn't surprising. When you go use this later it will blow up subsequent tables.

**Comment by tompollard** [comment]
Thanks, I'll take a look!

**Comment by tompollard** [comment]
Ah, I see, the duplicates appear because the data is merged back into the original subject_id index.

e.g. the admissions table has:

```
subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag
10003400,23559586,2137-08-04 00:07:00,2137-09-02 17:05:00,2137-09-02 17:05:00,URGENT,P99U21,TRANSFER FROM HOSPITAL,DIED,Medicare,ENGLISH,MARRIED,BLACK/AFRICAN AMERICAN,,,1
10003400,20214994,2137-02-24 10:00:00,2137-03-19 15:45:00,,URGENT,P60ZCO,TRANSFER FROM SKILLED NURSING FACILITY,CHRONIC/LONG TERM ACUTE CARE,Medicare,ENGLISH,MARRIED,BLACK/AFRICAN AMERICAN,,,0
```

So we end up with:

```
subject_id, race
10003400,BLACK/AFRICAN AMERICAN
10003400,BLACK/AFRICAN AMERICAN
```

**Comment by tompollard** [comment]
Right now, I don't think this issue should prevent us from continuing with creating the transformation (though I might be wrong). e.g. in the demo, we deal with it by aggregating on the link:

```
    - target_column: ethnicity
      transformation:
        type: link
        linked_table: admissions
        link_column: subject_id
        source_column: race
        aggregation:
          method: most_frequent
```

If we are treating the addition columns as a sequence, then we could consider supporting additional steps in the sequence. e.g. instead of:

```
tmp_subject_race:
  source_table: admissions
  target_table: tmp_subject_race
  columns:
    - target_column: subject_id
      transformation:
        type: copy
        source_column: subject_id
    - target_column: race
      transformation:
        type: aggregate
        source_columns:
          - subject_id
          - admittime
          - race
        group_by:
          - subject_id
        order_by: admittime
        aggregation: first
```

We could have:

```
tmp_subject_race:
  source_table: admissions
  target_table: tmp_subject_race
  sequence:
    - add_column: subject_id
      transformation:
        type: copy
        source_column: subject_id
    - add_column: race
      transformation:
        type: aggregate
        source_columns:
          - subject_id
          - admittime
          - race
        group_by:
          - subject_id
        order_by: admittime
        aggregation: first
   - dedupe
```
